services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        platform: linux/amd64
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "yourStrong(!)Password"
        ports:
            - "14333:1433"
    cms-portal:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - sqlserver
        ports:
            - "5001:80"
        environment:
            ASPNETCORE_URLS: http://+:80
            ASPNETCORE_ENVIRONMENT: Production
            ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=CMSDb;User Id=sa;Password=yourStrong(!)Password;Encrypt=False;TrustServerCertificate=False"


